services:
  bsuir-helper-embedder:
    image: ghcr.io/semantic-hallucinations/bsuir-helper-embedder:cuda
    ports:
      - "8081:8000"
    volumes:
      - huggingface_cache:/root/.cache/huggingface/hub
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 300s
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  qdrant-storage:
    image: docker.io/qdrant/qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_data:/qdrant/storage
  data-loader:
    build: .
    ports:
      - "8080:8000"
    env_file:
      - .env
    depends_on:
      bsuir-helper-embedder:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 300s
  # bsuir-site-parser:
  #   image: ghcr.io/semantic-hallucinations/bsuir-site-parser:latest
  #   depends_on:
  #     data-loader:
  #       condition: service_healthy
  #   env_file:
  #     - .env
  #   command: ["python", "main.py"]
volumes:
  huggingface_cache:
