services:
  data-loader:
    build: .
    ports:
      - "8080:8000"
    env_file:
      - .env
    depends_on:
      - qdrant-storage
      - bsuir-helper-embedder
  bsuir-helper-embedder:
    image: ghcr.io/semantic-hallucinations/bsuir-helper-embedder:cuda
    ports:
      - "8081:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  qdrant-storage:
    image: docker.io/qdrant/qdrant
    ports:
      - "6333:6333"
